web/router.ex
defmodule Pxblog.Router do
  use Pxblog.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Pxblog.CurrentUserPlug
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Pxblog do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    
    resources "/users", UserController do
      resources "/posts", PostController
    end
    resources "/sessions", SessionController, only: [:new, :create, :delete]

    resources "/posts", PostController, only: [:index] do
      resources "/comments", CommentController, only: [:create, :delete, :update]
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", Pxblog do
  #   pipe_through :api
  # end
end

web/models/post.ex
defmodule Pxblog.Post do
  use Pxblog.Web, :model

  schema "posts" do
    field :title, :string
    field :body, :string

    belongs_to :user, Pxblog.User
    has_many :comments, Pxblog.Comment

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(model, params \\ %{}) do
    model
    |> cast(params, [:title, :body])
    |> validate_required([:title, :body])
    |> strip_unsafe_body(params)
  end

  defp strip_unsafe_body(model, %{"body" => nil}) do
    model
  end

  defp strip_unsafe_body(model, %{"body" => body}) do
    {:safe, clean_body} = Phoenix.HTML.html_escape(body)
    model |> put_change(:body, clean_body)
  end

  defp strip_unsafe_body(model, _) do
    model
  end
end

web/controllers/post_controller.ex
defmodule Pxblog.PostController do
  use Pxblog.Web, :controller

  alias Pxblog.Post

  plug :authorize_user when action in [:new, :create, :update, :edit, :delete]
  plug :assign_user when not action in [:index]
  plug :set_authorization_flag

  def index(conn, %{"user_id" => _user_id}) do
    conn = assign_user(conn, nil)
    if conn.assigns[:user] do
      posts = Repo.all(assoc(conn.assigns[:user], :posts)) |> Repo.preload(:user)
      render(conn, "index.html", posts: posts)
    else
      conn
    end
  end

  def index(conn, _params) do
    posts = Repo.all(from p in Post,
                      limit: 5,
                      order_by: [desc: :inserted_at],
                      preload: [:user])
    render(conn, "index.html", posts: posts)
  end

  def new(conn, _params) do
    changeset = 
      conn.assigns[:user]
      |> build_assoc(:posts)
      |> Post.changeset()
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"post" => post_params}) do
    changeset =
      conn.assigns[:user]
      |> build_assoc(:posts)
      |> Post.changeset(post_params)

    case Repo.insert(changeset) do
      {:ok, _post} ->
        conn
        |> put_flash(:info, "Post created successfully.")
        |> redirect(to: user_post_path(conn, :index, conn.assigns[:user]))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    post = Repo.get!(assoc(conn.assigns[:user], :posts), id)
      |> Repo.preload(:comments)
    comment_changeset = post
      |> build_assoc(:comments)
      |> Pxblog.Comment.changeset()
    render(conn, "show.html", post: post, comment_changeset: comment_changeset)
  end

  def edit(conn, %{"id" => id}) do
    post = Repo.get!(assoc(conn.assigns[:user], :posts), id)
    changeset = Post.changeset(post)
    render(conn, "edit.html", post: post, changeset: changeset)
  end

  def update(conn, %{"id" => id, "post" => post_params}) do
    post = Repo.get!(assoc(conn.assigns[:user], :posts), id)
    changeset = Post.changeset(post, post_params)

    case Repo.update(changeset) do
      {:ok, post} ->
        conn
        |> put_flash(:info, "Post updated successfully.")
        |> redirect(to: user_post_path(conn, :show, conn.assigns[:user], post))
      {:error, changeset} ->
        render(conn, "edit.html", post: post, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    post = Repo.get!(assoc(conn.assigns[:user], :posts), id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(post)

    conn
    |> put_flash(:info, "Post deleted successfully.")
    |> redirect(to: user_post_path(conn, :index, conn.assigns[:user]))
  end

  defp assign_user(conn, _opts) do
    case conn.params do
      %{"user_id" => user_id} ->
        case Repo.get(Pxblog.User, user_id) do
          nil -> invalid_user(conn)
          user -> assign(conn, :user, user)
        end
      _ -> invalid_user(conn)
    end
  end

  defp invalid_user(conn) do
    conn
    |> put_flash(:error, "invalid_user!")
    |> redirect(to: page_path(conn, :index))
    |> halt
  end

  defp authorize_user(conn, _opts) do
    if is_authorized_user?(conn) do
      conn
    else
      conn 
      |> put_flash(:error, "You are not authorized to modify that post!")
      |> redirect(to: page_path(conn, :index))
      |> halt()
    end
  end

  defp is_authorized_user?(conn) do
    user = get_session(conn, :current_user)
    (user && (Integer.to_string(user.id) == conn.params["user_id"] || Pxblog.RoleChecker.is_admin?(user)))
  end

  defp set_authorization_flag(conn, _opts) do
    assign(conn, :author_or_admin, is_authorized_user?(conn))
  end
end

web/views/post_view.ex
defmodule Pxblog.PostView do
  use Pxblog.Web, :view

  def markdown(body) do
    body
    |> Earmark.to_html
    |> raw
  end
end

web/templates/post/edit.html.eex
<h2>Edit post</h2>

<%= render "form.html", changeset: @changeset,
                        action: user_post_path(@conn, :update, @user, @post) %>

<%= link "Back", to: user_post_path(@conn, :index, @user) %>

web/templates/post/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= label f, :body, class: "control-label" %>
    <%= textarea f, :body, class: "form-control", id: "body-editor" %>
    <%= error_tag f, :body %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

<link rel="stylesheet" href="//cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
<script src="//cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
<script type="text/javascript">var simplemde = new SimpleMDE();</script>

web/templates/post/index.html.eex
<div class="row">
  <div class="small-10 columns">
    <h1>Posts</h1>
  </div>
  <div class="small-2 columns text-right">
    <%= if current_user = @conn.assigns[:current_user] do %>
      <%= link "New post", to: user_post_path(@conn, :new, current_user.id), class: "button expanded large" %>
    <% end %>
  </div>
</div>

<%= for post <- @posts do %>
  <div class="row post">
    <div class="small-12 columns title">
      <h3><%= post.title %></h3>
    </div>
    <div class="small-12 columns">
      <small>
        Posted on <%= post.inserted_at %> by <%= link post.user.username, to: user_post_path(@conn, :index, post.user) %>
      </small>
    </div>
    <div class="small-12 columns">
      <%= markdown(post.body) %>
    </div>
    <%= if current_user = @conn.assigns[:current_user] do %>
      <div class="small-12 medium-4 columns">
        <%= link "Show", to: user_post_path(@conn, :show, post.user, post), class: "button expanded" %>
      </div>
      <div class="small-12 medium-4 columns">
        <%= link "Edit", to: user_post_path(@conn, :edit, post.user, post), class: "button warning expanded" %>
      </div>
      <div class="small-12 medium-4 columns">
        <%= link "Delete", to: user_post_path(@conn, :delete, post.user, post), method: :delete, data: [confirm: "Are you sure?"], class: "button alert expanded" %>
      </div>
    <% end %>
  </div>
<% end %>

web/templates/post/new.html.eex
<h2>New post</h2>

<%= render "form.html", changeset: @changeset,
                        action: user_post_path(@conn, :create, @user) %>

<%= link "Back", to: user_post_path(@conn, :index, @user) %>

web/templates/post/show.html.eex
<input type="hidden" id="post-id" value="<%= @post.id %>">

<h2>Show post</h2>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @post.title %>
  </li>

  <li>
    <strong>Body:</strong>
    <%= markdown(@post.body) %>
  </li>

</ul>

<hr>


<div class="comments">
  <h2>Comments</h2>
  <%= for comment <- @post.comments do %>
    <%= render Pxblog.CommentView, 
               "comment.html", 
               comment: comment, 
               author_or_admin: @conn.assigns[:author_or_admin],
               conn: @conn,
               post: @post 
    %>
  <% end %>
</div>

<hr>

<%= render Pxblog.CommentView, "form.html", changeset: @comment_changeset, action: post_comment_path(@conn, :create, @post) %>

<%= link "Edit", to: user_post_path(@conn, :edit, @user, @post) %>
<%= link "Back", to: user_post_path(@conn, :index, @user) %>